import { format } from "prettier";
import estree from "prettier/plugins/estree.js";
import tsplugin from "prettier/plugins/typescript.js";
import "./page.css";
import { render } from "./renderer.js";

const schemaRootPath = "#/components/schemas";
type APIInfo = {
    components: {
        schemas: Record<string, any>;
    };
};

async function getAPIJson(): Promise<APIInfo | null> {
    try {
        return fetch(
            "https://raw.githubusercontent.com/the-blue-alliance/the-blue-alliance/refs/heads/main/src/backend/web/static/swagger/api_v3.json"
        )
            .then((r) => r.json())
            .catch((e) => null);
    } catch {
        return null;
    }
}

const root = document.getElementById("root");
if (!root) throw new Error("root not found");
const status = document.createElement("div");
root.append(status);
const output = document.createElement("pre");
root.append(output);

const api = await getAPIJson();
if (!api) {
    status.textContent = "failed to fetch api schema";
    throw new Error("failed to fetch api schema");
}

const schemaRoot = api.components.schemas;
const dts = Object.entries(schemaRoot)
    // .slice(27, 28)
    .map(([key, val]) =>
        render({
            name: key,
            obj: val,
            topLevel: true
        })
    )
    .join("\n");
format(dts, {
    arrowParens: "always",
    objectWrap: "preserve",
    printWidth: 128,
    proseWrap: "preserve",
    quoteProps: "as-needed",
    semi: true,
    singleQuote: false,
    tabWidth: 4,
    trailingComma: "none",
    useTabs: false,
    parser: "typescript",
    plugins: [estree, tsplugin]
})
    .then((e) => {
        console.log(e);
        output.textContent =
            "// this file was generated by: https://moojor224.github.io/tba-api-docs-parser/\n" + e;
    })
    .catch((err) => {
        console.error(err);
        console.log(dts);
        status.textContent = err.toString();
    });
